
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4306/todoqu
    username: todoqu
    password: secret

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: rocks.isor.todoqu.hibernate.CustomPhysicalNamingStrategy
        domain-prefix: TDQ_